---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: lil-app
  namespace: flux-system
spec:
  interval: 30s
  url: https://niehaitao.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lil-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: lil-app
      sourceRef:
        kind: HelmRepository
        name: lil-app
  interval: 10m0s
  releaseName: lil-app

