apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lil-app
  namespace: flux-system
spec:
  chart:
    spec:
      version: 0.0.1
  values:
    image:
      registry: docker.io
      path: haitaonie/lil-app
      tag: 1.0.1 # {"$imagepolicy": "flux-deploy:lil-app:tag"}
    ingress:
      enabled: false