apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lil
  namespace: flux-system
spec:
  chart:
    spec:
      chart: lil-app
      sourceRef:
        name: lil-flight
  values:
    image:
      tag: 1.0.3 # {"$imagepolicy": "app:lil-flight:tag"}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: lil
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lil-flight
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: lil
  namespace: flux-system
spec:
  checkout:
    gitRepositoryRef:
      name: lil-flight
