name: ci-docker-image

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USER: haitaonie
  DOCKER_IMAGE: lil-app

  DOCKER_SOURCE: dev
  DOCKER_FILE: dev/app.dockerfile

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "docker image version"
        required: true
        default: "1.0.1"

jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=current::$(date +'%Y%m%d%H%M%S')"

      - name: Update index
        working-directory: ${{ env.DOCKER_SOURCE }}
        run: |
          sed 's/docker_tag/'${{ steps.date.outputs.current }}'/g' index.tmpl > index.html

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_USER }}/${{ env.DOCKER_IMAGE }}
          tag-sha: false
          tag-edge: false
          tag-latest: true
          tag-custom: ${{ github.event.inputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_IMAGE_RELEASE }}

      - name: Docker Build-Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ${{ env.DOCKER_FILE }}

      - name: Image tags
        run: echo "${{ steps.docker_meta.outputs.tags }}"
