name: ci-helm-chart

env:
  SOURCE_DIR: ops
  TARGET_OWNER: pop-cloud
  TARGET_REPO: pop-cloud.github.io
  TARGET_BRANCH: main
  TARGET_DEPLOY_KEY: ${{ secrets.HELM_CHART_RELEASE }}
  TARGET_DIR: helm-charts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ops/helm-chart-sources/**'

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git-repo
        uses: actions/checkout@v2

      - name: Publish helm-chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: ${{ env.SOURCE_DIR }}
          token: ${{ secrets.HELM_CHART_RELEASE }}
          charts_url: https://${{ env.TARGET_REPO }}
          owner: ${{ env.TARGET_OWNER }}
          repository: ${{ env.TARGET_REPO }}
          branch: ${{ env.TARGET_BRANCH }}
          target_dir: ${{ env.TARGET_DIR }}
          commit_username: ci-pop-cloud
